language: generic
sudo: false
env:
  global:
  - TEST_CMD='python -m pytest -vv -s tests'
  - MAIN_CMD='pipenv run'
  - SETUP_XVFB=true
  - PIPENV_IGNORE_VIRTUALENVS=1
matrix:
  fast_finish: true
  include:
  - os: linux
    env: PYTHON_VERSION=3.6
  - os: linux
    env: PYTHON_VERSION=3.7
  - os: osx
    language: generic
    env: PYTHON_VERSION=3.6
  - os: osx
    language: generic
    env: PYTHON_VERSION=3.7
before_install:
- git clone --depth 1 git://github.com/astropy/ci-helpers.git
- source ci-helpers/travis/setup_conda.sh
- source activate test
install:
- pip install pipenv --upgrade-strategy=only-if-needed
- pipenv install --dev .
script:
- "$MAIN_CMD python --version"
- "$MAIN_CMD $TEST_CMD"
- "$MAIN_CMD black . --check"
- "$MAIN_CMD flake8"
notifications:
  on_success: change
  on_failure: always
skip_commits:
  files:
  - docs/**/*
  - "**/*.rst"
  - "*.md"
  - ".gitignore"
  - appveyor.yml
  - LICENSE.txt
deploy:
  provider: pypi
  skip_existing: true
  user: j9ac9k
  password:
    - secure: U99UZ3bXUex3CVJ2RvyZgrJMM1IEnP8OrgMAunTvA9TVJBgCS21cBJ3Sgn/gC169cldz4nkENmJ23PnFPNLAsKQOCWAq4gaNQoWDopF/RP8RVbPoAWTA+a63O6wTYn6xD3HA4+lmPm3EaGw5YrlZbjGG1w724llsxAdVvjJm6Zbil+tgguALUuh+YOacxQhXW1wfIh4C/FnLqkSjE8wlCZi7dd0M/M46hUx0krACBamQyanBldI34MAyJAobRf3jpSkI/lp/GKSooaS7rXvZfcGcW+8BymsmTxd/Uxgzpwy1B4uT7wjcDmF5cEqFEEZpQHhF5BMELLaLzvSHSztd7e65R3n29Yo3jo7QcULzFIe7pd0GVILCMFzKlStNwoUWA+NSiSZtEzuA0I3tkFTYZ/yjSUs+GlHj3knSQTdP8V8NzsnnZtKdGQYx5HQ0LCe5dFhGnrboPyelWl7QUx0CYCek0xHub4HLauqAtA2nTkFcI6mupFTqrclMj+j5tNw6pMQJlP19KrhKat0unrsQbFgQk9/9PM1fGO0pkiOuVHCGIkYuxciiIbptwfGmNdQVPlmzzhvXOyO7nLtVCKdDvsdkD2A3TNP1ljbeXV5t51hNy3m1VLtiuCDO2Z/J0oIesxhV05AjREBVWEMdcN+1S9zTN5jpw9v1CMaO4afr23c=

  distributions: sdist bdist_wheel
  on:
    tags: true
