language: generic
sudo: false
env:
  global:
  - TEST_CMD='python -m pytest -vv -s tests'
  - MAIN_CMD='pipenv run'
  - SETUP_XVFB=true
  - PIPENV_IGNORE_VIRTUALENVS=1
matrix:
  fast_finish: true
  include:
  - os: linux
    env: PYTHON_VERSION=3.6
  - os: linux
    env: PYTHON_VERSION=3.7
  - os: osx
    language: generic
    env: PYTHON_VERSION=3.6
  - os: osx
    language: generic
    env: PYTHON_VERSION=3.7
before_install:
- git clone --depth 1 git://github.com/astropy/ci-helpers.git
- source ci-helpers/travis/setup_conda.sh
- source activate test
install:
- pip install pipenv --upgrade-strategy=only-if-needed
- pipenv install --dev .
script:
- "$MAIN_CMD python --version"
- "$MAIN_CMD $TEST_CMD"
- "$MAIN_CMD black . --check"
- "$MAIN_CMD flake8"
notifications:
  on_success: change
  on_failure: always
skip_commits:
  files:
  - docs/**/*
  - "**/*.rst"
  - "*.md"
  - ".gitignore"
  - appveyor.yml
  - LICENSE.txt
deploy:
  provider: pypi
  user: j9ac9k
  password: $PYPI_PASSWORD
  distributions: "sdist bdist_wheel"
  skip_existing: true
  on:
    tags: true
    repo: j9ac9k/timeview
