language: generic
sudo: false
env:
  global:
  - TEST_CMD='python -m pytest -vv -s tests'
  - MAIN_CMD='pipenv run'
  - SETUP_XVFB=true
  - PIPENV_IGNORE_VIRTUALENVS=1
  - secure: dz0S9m1PyA+Phee3LOHCbU56WHx2fIGg74rEDL7GyOiSUouAxg8o6lqLn3lrd0Xnre/IqiplTGwyshH8gbPlb7w1vzAi962vZwRf3iDaZpIIs8NKZ3FIZohPv7o/uTa9C+Yg97jUQOLJvJUlCReGSflIIC98c8K+axAmhPWgW7nTAAA2Fu9Ux5rrwk1i9HV6LH7gKmAjf8e3+N7mRTXlsh9HRxZFMypcP+pi1N+pKdWtlUaYAl6sTrWETZr1uPJ396OCFC2lIft/mBnNDkmNSkZlLbqbOML24xjeivRuxoYNFogzJar3//QzTI29uZV1rhV8mDuSZMMqXgiDZ8XGnwl3K34PC1NiUxAf+NzX7Sb1I+PL14DNTl5lOYB1p+gAr2Co+k79CI4pjib8zbopjTpv4zuD3mEcathcH7BPfTZe1INu8gXrAZ2Vvg/a9Hd+jK41AcgWYCHI7kUjPrj85Vi+ei7zxdQ1oQhTcszhUgfKOasuF0SfnpAj1CPcIj68C8rvzEWM2GQLYLDPytsV6EFNIDgmXIE7n0CxSexf/uAtPULj8pcPsOWZnUbMxu65wmDB7cTaK+upEVFM69BSZCR02zHzPhaGGTYEcyYvqbJBhJGEBBQ/Zin4XTvdWt8YHKJDfYQYACTFq3Tep5SOXknPVvKkXQgRh5aqDkiPDog=
matrix:
  fast_finish: true
  include:
  - os: linux
    env: PYTHON_VERSION=3.6
  - os: linux
    env: PYTHON_VERSION=3.7
  - os: osx
    language: generic
    env: PYTHON_VERSION=3.6
  - os: osx
    language: generic
    env: PYTHON_VERSION=3.7
before_install:
- git clone --depth 1 git://github.com/astropy/ci-helpers.git
- source ci-helpers/travis/setup_conda.sh
- source activate test
install:
- pip install pipenv --upgrade-strategy=only-if-needed
- pipenv install --dev .
script:
- "$MAIN_CMD python --version"
- "$MAIN_CMD $TEST_CMD"
- "$MAIN_CMD black . --check"
- "$MAIN_CMD flake8"
notifications:
  on_success: change
  on_failure: always
skip_commits:
  files:
  - docs/**/*
  - "**/*.rst"
  - "*.md"
  - ".gitignore"
  - appveyor.yml
  - LICENSE.txt
deploy:
  provider: pypi
  skip_existing: true
  user: j9ac9k
  password:
    secure: EdGAfjDf/z3cj97UGkkKMxrsSpBXl30ZSKCvjKlj6FEN0SJAc10ka6Q/pw9Avpp+WKAEUYpMlk5SCNxt7larw3hi8siAFQV3j4j4JXLnp34pD9Yk0JFgmfDe7Zux5fWbcbVFEgdsy5NCnlEOZIgqdpoeHBYkMDnusyI1bcGv7B73tW/4Exluwg54tBWB9mARjLD5aXI1ybUzDVgBi+py/ZojufZBmtDWpHC783mqfQU9r7UAeUjpgWqGOBh/1vDYzcpoAClwamEYm/5Brpi+zeHLS87Li/BI7a89Mur++zP5P0yaAAqncbgwbIurKAbub1k+TSoSA3DMFb41csYnyg0SfkAZHPgum5AHfKUWY1In0ykgmRJLx5cyZe6wTxBLLPg5VgaFnnVCMBHsorBLWIwLZFlRwP9kU1oZGJHFzaNc5VR3X9wAN8ANmbAab+pq8MvTo/5Uqii5sAwQKarP80hkEeWRKS9LjZzwoZusP/ejH0C8a/DYFvwipzqfcjZ4bMxxpXpF64s7Sqkeer60PV0ZCVRf8v2SD1DLaPHdKw0A5+xFnHIVQUmCJIfMTAFlKbT1ULYGMUIWPoDc82BuzTlTWB5JM7fMWPSKadFc9ZwID7C3SCWQCPV1KZpSAvHOu6cKrsnrmirfrossAElJyJTtsB3yQf6qAYTr4iaKFTM=
  distributions: sdist bdist_wheel
  on:
    tags: true
