language: python

sudo: false

python:
  - "3.6"

install:
  - pip install ".[test]"

# before_script:
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
#   - sleep 3 # give xvfb some time to start

script: xvfb-run make pytest