environment:
  global:
    PYTHON: "C:\\Python36-x64"
    PYTHON_ARCH: "64"

platform:
  -x64

install:
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
      https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
      Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
        throw "There are newer queued builds for this pull request, failing early." }
  - "pip install -e .[test]"

build: off

test_script:
  -  "build.cmd %PYTHON%\\python.exe -m pytest -v tests/"

artifacts:
  - path: dist\*

skip_tags: true